name: Say Hello 

on:
    push:
        branches: 
            - master
            
jobs: 
    hello_world: 
        runs-on: windows-latest
        steps: 
            - name: Echo the message
              run: |
                echo "Hello World!" 
